import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import SideNavbar from "@/components/SideNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("flex min-h-screen bg-white", inter.className, {
          "debug-screens": process.env.NODE_ENV === "development",
        })}
      >
        {/* sidebar */}
        <SideNavbar />
        {/* main page */}
        <div className="flex-1 p-8">{children}</div>
      </body>
    </html>
  );
}
