import { FC, ReactNode } from "react";
import "../globals.css";
import { Metadata } from "next";

interface LayoutProps {
  children: ReactNode;
}
export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "TNB-SWITCHWISE",
    template: "%s | TNB-SWITCHWISE",
  },
  description: "Generated by create next app",
};

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <html>
      <body>
      <div className="relative min-h-screen flex items-center justify-center bg-gray-100">
      <div className="relative w-full max-w-md">
        {children}
      </div>
    </div>
      </body>
    </html>

  );
};

export default Layout;
